stages:

  ingest:
    cmd: python src/data/ingestion.py
    deps:
      - src/data/ingestion.py
      - data/raw/Churn_Modelling.csv
    params:
      - data
    outs:
      - data/interim/ingested.csv

  preprocess:
    cmd: python src/data/preprocessing.py
    deps:
      - src/data/preprocessing.py
      - data/interim/ingested.csv
    params:
      - preprocess
    outs:
      - data/processed/train.pkl
      - data/processed/test.pkl

  train:
    cmd: python src/model/train.py
    deps:
      - src/model/train.py
      - data/processed/train.pkl
      - data/processed/test.pkl
    params:
      - model
      - training
    outs:
      - artifacts/train_output.json

  evaluate:
    cmd: python src/model/evaluate.py
    deps:
      - src/model/evaluate.py
      - artifacts/train_output.json
    params:
      - evaluation
    outs:
      - artifacts/eval_output.json

  register:
    cmd: python src/model/register.py
    deps:
      - src/model/register.py
      - artifacts/eval_output.json
    params:
      - registry

  export_model:
    cmd: python src/model/export_model.py
    deps:
      - src/model/export_model.py
    outs:
      - model/churn_model.keras
      - model/metadata.json